# Generated by Django 5.2.7 on 2025-12-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='long_Para1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='description',
            name='long_Para2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='description',
            name='long_Para3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='description',
            name='short_description',
            field=models.CharField(max_length=130),
        ),
    ]
